services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\UserBundle\Controller\:
        resource: '../../Controller/*'

    c975L\UserBundle\Form\:
        resource: '../../Form/*'

    c975L\UserBundle\Listener\:
        resource: '../../Listener/*'

    c975L\UserBundle\Service\:
        resource: '../../Service/*'

    c975L\UserBundle\Twig\:
        resource: '../../Twig/*'
